### ISSUE TITLE
Api choice?

### ISSUE THREAD

**Issue by mikecann** [elegos/typesafe-actions-reducer-builder#1]
Hey,

Love the concept of the library, removing some of the boiler when using `typesafe-actions` and `immer`.

I am just wondering about the API choice however. I would have loved to see something simpler such as:

```
  const myReducer = createReducer<AppState, AppActions>(defaultState())
    .handle(increment, (state, action) => {state + 1})
    .handle(decrement, (state, action) => {state - 1})
    .handle([anotherAction, andAnotherAction], (state, action) => {state = 999})
```

Thoughts?

**Comment by elegos** [comment]
I'm sorry to reply this late, but I must have missed the notification u.u.

However if you're still interested in a response, the problem resides in the typesafe-action's `ActionCreatorBuilder` interface, which is templated up to three types (`<TypeConstant, TPayload, TMeta>`).

The result though is similar to your input, because it's mainly something like this:

```typescript
const myReducer = createReducerBuilder(defaultState())
  .handle(increment).reducer((state, action) => {state + 1})
  .handle(decrement).reducer((state, action) => {state - 1})
  .build()
```

The differences are that forcing a `reducer` method in `ReducerBuilderHandler` allows for less bug-prone code in case of custom handler (if you'd ever need to create one), and that I follow the builder design pattern (and thus the `build()` call in the end). The build pattern here is very straight to be honest, because when you call it you can easily wrap all the handlers and apply a second pattern, i.e. the chain of responsibility (which is what redux does in its core).

I'm also not entirely sure whether a templated `handle` could manage the (structured) type of the first argument as types of state and action parameters of the 2nd parameter (the reducer). Thus you can see how I simplified the library's code by dividing the handle from the reducer.

**Comment by mikecann** [comment]
Cool, thanks mate :)
